# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: Release
run-name: wasi-demo-app@${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version of the crate to release. (e.g., 1.2.3)"
        type: string
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
 release-wasi-demo-app:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup build env
        run: ./scripts/setup-linux.sh
      - name: Install Rust and wasm32-wasi target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-wasi
          override: true
      - name: Build oci tarballs
        run: |
          sudo make test-image  
          sudo make test-image/oci
          ls -l dist/
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - uses: oras-project/setup-oras@v1
      - run: |
          oras push ghcr.io/containerd/wasi-demo-app:v${{ inputs.version }} dist/img.tar
          oras push ghcr.io/containerd/wasi-demo-app-oci:v${{ inputs.version }} dist/img-oci.tar
          oras push ghcr.io/containerd/wasi-demo-app-oci-artifact:v${{ inputs.version }} dist/img-oci-artifact.tar 
